# Generated by Django 3.2.8 on 2024-07-12 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 9, 17, 26, 430777))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 9, 17, 26, 430801))),
            ],
            options={
                'db_table': 'Countes',
            },
        ),
        migrations.CreateModel(
            name='Dinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_openId', models.CharField(default='', max_length=256)),
                ('healthy_star', models.SmallIntegerField(default=0, max_length=2)),
                ('delicious_star', models.SmallIntegerField(default=0, max_length=2)),
                ('friends_stars', models.TextField(default='[]')),
                ('location', models.CharField(default='', max_length=256)),
                ('pic_url', models.CharField(default='', max_length=256)),
                ('file_id', models.CharField(default='', max_length=256)),
                ('org_file_id', models.CharField(default='', max_length=256)),
                ('type', models.CharField(default='', max_length=32)),
                ('date', models.DateField(default=datetime.date(2024, 7, 12))),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 9, 17, 26, 432568))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 9, 17, 26, 432587))),
            ],
            options={
                'db_table': 'Dinners',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=256)),
                ('open_id', models.CharField(default='', max_length=256)),
                ('avatar_url', models.CharField(default='', max_length=256)),
                ('phone', models.CharField(default='', max_length=32)),
                ('friends', models.TextField(default='[]')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 9, 17, 26, 431522))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 9, 17, 26, 431543))),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]