# Generated by Django 3.2.8 on 2025-03-01 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_auto_20240716_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_openId', models.CharField(default='', max_length=256)),
                ('text', models.CharField(default='', max_length=1024)),
                ('category', models.CharField(default='', max_length=256)),
                ('positive', models.IntegerField(default=3)),
                ('date', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UserNotes',
            },
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 5, 5, 22, 558583)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 5, 5, 22, 558601)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 5, 5, 22, 612766)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 5, 5, 22, 612795)),
        ),
    ]