# Generated by Django 3.2.8 on 2025-12-14 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0004_auto_20250306_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('stock', 'Stock'), ('house', 'House')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shares', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_asset',
            },
        ),
        migrations.CreateModel(
            name='AssetCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_actual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_asset_correction',
            },
        ),
        migrations.CreateModel(
            name='FixedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('frequency', models.CharField(default='monthly', max_length=50)),
                ('date_value', models.IntegerField(help_text='Day of the month')),
                ('account', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_fixed_item',
            },
        ),
        migrations.CreateModel(
            name='FutureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('stock', 'Stock')], max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shares', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('inactive_icon', models.CharField(default='circle', max_length=50)),
                ('active_icon', models.CharField(default='checked', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_future_item',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('periods', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('method', models.CharField(choices=[('equal_principal', 'Equal Principal'), ('equal_principal_interest', 'Equal Principal and Interest')], default='equal_principal', max_length=50)),
                ('repayment_date', models.IntegerField(help_text='Day of the month (1-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_loan',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_large', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_transaction',
            },
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 50, 39, 745367)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 50, 39, 745389)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 50, 39, 745931)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 4, 50, 39, 745948)),
        ),
    ]