# Generated by Django 3.2.8 on 2025-12-14 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0005_auto_20251214_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='user_openId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assetcorrection',
            name='user_openId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fixeditem',
            name='user_openId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='futureitem',
            name='user_openId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='user_openId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_openId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 6, 46, 5, 702728)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 6, 46, 5, 702747)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 6, 46, 5, 703238)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 6, 46, 5, 703251)),
        ),
    ]