# Generated by Django 3.2.8 on 2025-12-14 07:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0006_auto_20251214_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futureitem',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='futureitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 7, 57, 26, 26161)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 7, 57, 26, 26180)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 7, 57, 26, 26646)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 7, 57, 26, 26658)),
        ),
    ]