# Generated by Django 3.2.8 on 2025-12-28 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0008_auto_20251214_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 5, 21, 28, 164184)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 5, 21, 28, 164202)),
        ),
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 5, 21, 28, 164742)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 5, 21, 28, 164756)),
        ),
    ]